language: node_js
node_js:
  - "0.12"
sudo: true # turn off containers to support validator
script: make travis
matrix:
  fast_finish: true
notifications:
  email:
    - joshua@mervine.net
    - bootstrap@maxcdn.com
