authors:
- Joshua Mervine
- Justin Dorfman

description: Bootstrap CDN

favicon:
    # ico must be filesystem path, not web path
    ico: "public/images/favicon.ico"
    png: "/images/favicon.png"

google_analytics:
    account_id: UA-32253110-1
    domain_name: bootstrapcdn.com

####
# Note: stylesheets and javascript will be loaded
# in the order they are specified.

stylesheets:
- "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css"
- "/stylesheets/bootstrap-cdn.css"
- "/stylesheets/docs.css"

javascript:
    # scripts specified in the before group will be loaded
    # as blocking scripts inside the head tag
    #before:
    #
    # scripts specified in the after group will be loaded
    # as blocking scripts at the bottom of the page
    after:
    - "//code.jquery.com/jquery-1.10.1.min.js"
    - "//platform.twitter.com/widgets.js"
    - "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"


# vim: ft=yaml sw=4 sts=4 et:
